language: node_js
node_js:
- node
branches:
  only:
  - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
    - chaos@xuyuanxiang.cn
    on_success: never
    on_failure: always
before_deploy: npm run build
deploy:
  provider: npm
  email: chaos@xuyuanxiang.cn
  api_key:
    secure: TJ35w+KhwBeZyReWPKKM2GfrWNWrl9sNAtGchibUNkTnpbeUoumHQI7qcilxEk739wONuhmf5xX/YcjYoKPpT4950uu9/K+11AcwCPjR8f3czlWP1mF7hzhjw9Ziw1vEz6uGVNHQvUBFZ1rhre43zT6PLsK04exP6cCDJzeMgm/LgK3Dd0oKIV3eTl32k1GUz5qqx1YEi07iOMjEznw21MEaPcyu+8nbyExaIQSabpfD+qUiTy8pUd0xUGhvpHx8QBTC08TW/QdZ3LS4Ub9QVeM6d6gdTn+ITosgq8UdWqMfJeEAlhmKrvkqpsro7yN8AUcWOGL1NuBu0UUBjqYXlA29yw773/focWW1x5QuMjJ63QTLkDNv0SodLDajMpnSEL+F5fTITVMTN4Li9iG0nG3Q3XI98g6vCwXWF1PmKqTDNdP4e99n2M/h5Pl1QJAAP9rd4C20mD8jJyoKWlSVtY3ibdIlfz0UP+Qmz8xqUtwo/vBZWeqdt51SpCYZHR408XnERBWiVW7ll65Gmww3z/QLpCJvkXr7I/OE5Xi1TOCq8RIF48dZyTL4nsvrcB744p7qUsqw7xUjnBvRX+u6Q50oz7GUscjMwW9pMI1MiK42Ho/vhdaXTgUVArITVOOk+0vxblB2A8C7cbstua1omjQMKRtDNYJKk5xIdSCFNNo=
  on:
    tags: true
    repo: xuyuanxiang/heirloom-api-plugin
